export const SWR_KEY = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_USER_STATUS: "GET_ALL_USER_STATUS",
  GET_ALL_FEEDBACK: "GET_ALL_FEEDBACK",
  GET_ALL_FEEDBACK_STATUS: "GET_ALL_FEEDBACK_STATUS",
  GET_ALL_FEEDBACK_DETAILS: "GET_ALL_FEEDBACK_DETAILS",
};
