export const SWR_KEY = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_USER_STATUS: "GET_ALL_USER_STATUS",
  GET_ALL_FEEDBACK: "GET_ALL_FEEDBACK",
  GET_ALL_FEEDBACK_STATUS: "GET_ALL_FEEDBACK_STATUS",
  GET_ALL_FEEDBACK_DETAILS: "GET_ALL_FEEDBACK_DETAILS",
  GET_ALL_ROLES: "GET_ALL_ROLES",
  GET_ALL_REAL_ESTATES: "GET_ALL_REAL_ESTATES",
  GET_SINGLE_REAL_ESTATE: "GET_SINGLE_REAL_ESTATE",
  GET_ALL_PERMISSION: "GET_ALL_PERMISSION",
 
};
